__author__ = 'Ryan James Kennedy'
__author_email__ = 'ryan.kennedy@skane.se'
__copyright__ = 'Copyright 2023'
__description__ = 'A tool for mongo db.'
__email__ = 'ryan.kennedy@skane.se'
__license__ = 'GPL3'
__maintainer__ = 'Ryan James Kennedy'
__maintainer_email__ = 'ryan.kennedy@skane.se'
__name__ = 'mongtool'
__python_requires__ = '>=3.11'
__status__ = 'Production'
__title__ = 'MongTool'
__url__ = 'https://github.com/ryanjameskennedy/MongTool'
__version__ = '0.0.1'