__author__ = 'Ryan James Kennedy'
__author_email__ = 'ryan.kennedy@skane.se'
__copyright__ = 'Copyright 2023'
__description__ = 'A tool for mongo db and JASEN.'
__email__ = 'ryan.kennedy@skane.se'
__license__ = 'GPL3'
__maintainer__ = 'Ryan James Kennedy'
__maintainer_email__ = 'ryan.kennedy@skane.se'
__name__ = 'jasentool'
__python_requires__ = '>=3.11'
__status__ = 'Production'
__title__ = 'jasentool'
__url__ = 'https://github.com/ryanjameskennedy/jasentool.git'
__version__ = '0.1.0'
